# Generated by Django 3.2 on 2023-04-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
